[package] 
name = "blink_led" 
version = "0.1.0"
edition = "2021" 

[dependencies] 
cortex-m = "0.7" 
cortex-m-rt = "0.7" 
teensy4-bsp = "0.3" 
panic-halt = "0.2"

[profile.release] 
lto = true
codegen-utils = 1
debug = true

